libname stat512 "M:\biostats 512";
*q1 descriptives;
proc means data=stat512.attain_kid; run;
proc means data=stat512.attain_neigh; run;
*q2 boxplots;
proc sgplot data=stat512.attain_kid;
vbox attain/ category=dadunemp;
run;
proc sgplot data=stat512.attain_kid;
vbox attain/ category=momed;
run;
proc sgplot data=stat512.attain_kid;
vbox attain/ category=male;
run;
proc sgplot data=stat512.attain_kid;
vbox attain/ category=dadocc;
run;
*q3 merge;
proc sort data=stat512.attain_kid; by neighid; run;
proc sort data=stat512.attain_neigh; by neighid; run;
data stat512.merge;
merge stat512.attain_kid stat512.attain_neigh;
by neighid;
run;
proc means data=stat512.attain_kid noprint; 
by neighid;
output out=stat512.mean mean(attain)=mn_attain;
run;
proc means data=stat512.mean; run;
proc sgplot data=stat512.mean;
scatter y=mn_attain x=neighid;
run;
proc sort data=stat512.mean; by neighid; run;
data stat512.full;
merge stat512.merge stat512.mean;
by neighid;
run;
proc means data=stat512.full; run;
proc sgplot data=stat512.full;
scatter y=mn_attain x=deprive;
run;
*q4 fit random int model;
proc mixed data=stat512.attain_kid covtest cl;
class neighid;
model attain= /solution ddfm=sat;
random int/subject=neighid;
run;
*q5 fit level 1 model;
proc mixed data=stat512.attain_kid covtest cl;
class neighid;
model attain= dadunemp dadocc momed male/solution ddfm=sat;
random int/subject=neighid;
run;
*q6 fit level 2;
proc mixed data=stat512.merge covtest cl;
class neighid;
model attain= dadunemp dadocc momed male deprive/solution ddfm=sat;
random int/subject=neighid;
run;
*q7 fit with dadocc#deprive;
*should dadocc be random slope??;
ods graphics on;
proc mixed data=stat512.merge covtest cl plots=(residualpanel) plots(maxpoints=8000);
class neighid;
model attain= dadunemp dadocc momed male deprive dadocc*deprive/solution ddfm=bw;
random int dadocc/subject=neighid solution type=vc;
ods output solutionR=stat512.solutionRdat;
run;
ods graphics off;
*q8;
ods graphics on;
ods listing;
proc univariate data=stat512.solutionRdat;
where effect="Intercept";
var estimate;
histogram/ normal kernel;
qqplot/normal(mu=est sigma=est);
run;
ods graphics off;
